apiVersion: v1
kind: Service
metadata:
  name: airflow-api-server-serivce
spec:
  selector:
    app: airflow-api-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80