apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  run_db_migration_boolean: "1" # 0=false, 1=true
  create_webserver_user_boolean: "1" # 0=false, 1=true
  ingress_host: "localhost:8080"