apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow-webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: airflow-webserver
        image: airflow-webserver:latest
        ports:
        - containerPort: 8080
        env:
        - name: RUN_DB_MIGRATION_BOOLEAN
          valueFrom:
            configMapKeyRef:
              name: airflow-config
              key: run_db_migration_boolean
        - name: AIRFLOW__WEBSERVER__BASE_URL
          valueFrom:
            configMapKeyRef:
              name: airflow-config
              key: ingress_host
        - name: CREATE_WEBSERVER_USER_BOOLEAN
          valueFrom:
            configMapKeyRef:
              name: airflow-config
              key: create_webserver_user_boolean
        - name: AIRFLOW_WEBSERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: airflow_webserver_username
        - name: AIRFLOW_WEBSERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: airflow_webserver_password
        - name: AIRFLOW_WEBSERVER_EMAIL
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: airflow_webserver_email
              key: airflow_webserver_password
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: database_connection_string
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: airflow_fernet_key